### ISSUE TITLE
unemployment chart values should be discrete no continuous

### ISSUE THREAD

**Issue by genelewis** [genelewis/countySTATS#7]
The unemployment chart is displaying the values as if they were continuous, so for example as you mouse from 2014 to 2016 it shows precise numbers for wherever you are on the line. However, the data should be discrete annual numbers. The population chart does this correctly, jumping the highlighted point by ten year intervals as you move.

**Comment by aaronkrusniak** [comment]
Should be fixed in the latest patch, cc1985d34fc4e62c68211d6ac34173de87dcd520.
